import type { Post } from "@/lib/content/types";
import { getBlogImage } from "@/lib/content/blog-images";

function post(
  i: number,
  data: Omit<Post, "id" | "featuredImage" | "status" | "isFeatured"> & {
    featured?: boolean;
  },
): Post {
  return {
    id: String(i),
    featuredImage: i % 3 === 0 ? undefined : getBlogImage(i),
    status: "published",
    isFeatured: data.featured ?? i <= 3,
    ...data,
  };
}

export const postsSeed: Post[] = [
  post(1, {
    slug: "bang-gia-lap-wifi-vnpt-2026",
    title: "Bảng giá lắp WiFi VNPT 2026 — cập nhật và cách đọc đúng",
    excerpt:
      "Tổng hợp cách đọc bảng giá WiFi VNPT: phí hòa mạng, giá nội/ngoại thành và mẹo chọn gói không bị phát sinh.",
    content: `<p>Bảng giá WiFi VNPT thay đổi theo từng thời điểm khuyến mãi. Khi xem giá, cần chú ý ba phần: cước hàng tháng, phí hòa mạng và chi phí thiết bị bổ sung như Mesh.</p><h2>Giá nội thành và ngoại thành</h2><p>TP.HCM chia giá nội/ngoại thành. Quận 12 thuộc nội thành nên áp giá cột nội thành trên bảng giá. Luôn xác nhận địa chỉ trước khi chốt.</p><h2>Phí hòa mạng</h2><p>Phí hòa mạng thường thu một lần khi đăng ký mới. Tôi luôn báo rõ trước khi khách ký.</p><h2>Mẹo tiết kiệm</h2><p>Chọn gói đúng nhu cầu thay vì gói cao nhất. Nhà 2–3 người thường không cần 1 Gbps.</p>`,
    category: "wifi",
    tags: ["bảng giá", "WiFi VNPT", "2026"],
    seoTitle: "Bảng giá lắp WiFi VNPT 2026 | Cập nhật TP.HCM",
    seoDescription: "Cách đọc bảng giá WiFi VNPT 2026, phí hòa mạng và chọn gói phù hợp tại TP.HCM.",
    readingTime: 4,
    publishedAt: "2026-06-01",
    relatedPostSlugs: ["lap-wifi-vnpt-mat-bao-lau", "wifi-vnpt-300mbps-co-du-dung-khong"],
    featured: true,
  }),
  post(2, {
    slug: "lap-wifi-vnpt-mat-bao-lau",
    title: "Lắp WiFi VNPT mất bao lâu? Timeline thực tế tại TP.HCM",
    excerpt: "Từ lúc đăng ký đến khi có mạng: timeline 1–3 ngày và yếu tố ảnh hưởng tốc độ lắp.",
    content: `<p>Thời gian lắp WiFi VNPT phụ thuộc hạ tầng, lịch kỹ thuật và thủ tục. Trung bình 1–3 ngày làm việc.</p><h2>Các bước và thời gian</h2><p>Ngày 1: Gửi hồ sơ, kiểm tra hạ tầng. Ngày 2–3: Kỹ thuật lắp modem và test tốc độ.</p><h2>Khu vực Quận 12</h2><p>Quận 12 thường hẹn nhanh hơn vì tôi hỗ trợ trực tiếp tại khu vực.</p>`,
    category: "wifi",
    tags: ["lắp đặt", "thời gian"],
    seoTitle: "Lắp WiFi VNPT mất bao lâu? | Timeline TP.HCM",
    seoDescription: "WiFi VNPT lắp mất bao lâu tại TP.HCM? Timeline thực tế và mẹo rút ngắn thời gian.",
    readingTime: 3,
    publishedAt: "2026-06-02",
    relatedPostSlugs: ["lap-wifi-vnpt-can-giay-to-gi"],
  }),
  post(3, {
    slug: "lap-wifi-vnpt-can-giay-to-gi",
    title: "Lắp WiFi VNPT cần giấy tờ gì?",
    excerpt: "CMND, hộ khẩu, giấy tờ nhà thuê — chuẩn bị đúng để không bị trì hoãn lắp đặt.",
    content: `<p>Giấy tờ cơ bản: CMND/CCCD và số điện thoại liên hệ. Nhà thuê có thể cần thêm thông tin chủ nhà.</p><h2>Trường hợp đặc biệt</h2><p>Căn hộ dịch vụ, nhà trọ nhiều phòng — nên nói rõ mục đích sử dụng để chọn gói phù hợp.</p>`,
    category: "wifi",
    tags: ["giấy tờ", "đăng ký"],
    seoTitle: "Lắp WiFi VNPT cần giấy tờ gì?",
    seoDescription: "Danh sách giấy tờ cần chuẩn bị khi đăng ký lắp WiFi VNPT tại TP.HCM.",
    readingTime: 3,
    publishedAt: "2026-06-03",
    relatedPostSlugs: ["bang-gia-lap-wifi-vnpt-2026"],
  }),
  post(4, {
    slug: "wifi-vnpt-300mbps-co-du-dung-khong",
    title: "WiFi VNPT 300 Mbps có đủ dùng không?",
    excerpt: "Phân tích 300 Mbps cho 2–6 thiết bị: học online, xem phim, camera.",
    content: `<p>300 Mbps đủ cho hộ 2–4 thiết bị dùng cơ bản. Xem phim HD, học online 1–2 người cùng lúc vẫn ổn.</p><h2>Khi nào cần nâng gói?</h2><p>Đông thiết bị, xem 4K nhiều TV, livestream hoặc văn phòng nhỏ nên 500 Mbps trở lên.</p>`,
    category: "wifi",
    tags: ["300 Mbps", "tốc độ"],
    seoTitle: "WiFi VNPT 300 Mbps có đủ dùng không?",
    seoDescription: "Gói 300 Mbps VNPT có đủ cho gia đình không? Phân tích theo số thiết bị.",
    readingTime: 3,
    publishedAt: "2026-06-04",
    relatedPostSlugs: ["wifi-mesh-la-gi"],
  }),
  post(5, {
    slug: "wifi-yeu-phai-lam-gi",
    title: "WiFi yếu phải làm gì? 7 bước xử lý nhanh tại nhà",
    excerpt: "Khắc phục WiFi yếu: vị trí modem, nhiễu sóng, số thiết bị và khi nào cần Mesh.",
    content: `<p>WiFi yếu thường do vị trí modem, tường dày, quá nhiều thiết bị hoặc modem cũ.</p><h2>7 bước xử lý</h2><ol><li>Đặt modem cao, thoáng</li><li>Restart modem</li><li>Giảm thiết bị dùng cùng lúc</li><li>Đổi kênh WiFi</li><li>Kiểm tra dây LAN</li><li>Test speed gần modem</li><li>Cân nhắc Mesh nếu nhà rộng</li></ol>`,
    category: "troubleshooting",
    tags: ["WiFi yếu", "khắc phục"],
    seoTitle: "WiFi yếu phải làm gì? | 7 bước xử lý nhanh",
    seoDescription: "Hướng dẫn xử lý WiFi yếu tại nhà trước khi gọi kỹ thuật.",
    readingTime: 5,
    publishedAt: "2026-06-05",
    relatedPostSlugs: ["modem-wifi-nen-dat-o-dau", "wifi-mesh-la-gi"],
  }),
  post(6, {
    slug: "modem-wifi-nen-dat-o-dau",
    title: "Modem WiFi nên đặt ở đâu để sóng mạnh?",
    excerpt: "Vị trí đặt modem ảnh hưởng lớn đến sóng WiFi — góc nhà, tầng, tránh tủ kim loại.",
    content: `<p>Đặt modem ở trung tâm ngôi nhà, cao 1–1.5m, tránh góc khuất và thiết bị phát nhiễu như lò vi sóng.</p><h2>Nhà nhiều tầng</h2><p>Đặt modem tầng giữa hoặc dùng Mesh thay vì đặt sát tường ngoài cùng.</p>`,
    category: "wifi",
    tags: ["modem", "vị trí"],
    seoTitle: "Modem WiFi nên đặt ở đâu?",
    seoDescription: "Mẹo đặt modem WiFi đúng vị trí để sóng mạnh hơn trong nhà.",
    readingTime: 3,
    publishedAt: "2026-06-06",
    relatedPostSlugs: ["wifi-yeu-phai-lam-gi"],
  }),
  post(7, {
    slug: "wifi-mesh-la-gi",
    title: "WiFi Mesh là gì? Có cần cho nhà bạn không?",
    excerpt: "Giải thích WiFi Mesh đơn giản và so sánh với router phụ truyền thống.",
    content: `<p>WiFi Mesh là hệ thống nhiều node phủ sóng đồng nhất, tự chuyển mạng khi di chuyển trong nhà.</p><h2>Ai nên dùng?</h2><p>Nhà 2–3 tầng, diện tích trên 80m², nhiều phòng ngăn — Mesh thường hiệu quả hơn router phụ.</p>`,
    category: "wifi",
    tags: ["Mesh", "WiFi"],
    seoTitle: "WiFi Mesh là gì? | Giải thích dễ hiểu",
    seoDescription: "WiFi Mesh là gì, khác router phụ thế nào và ai nên dùng?",
    readingTime: 4,
    publishedAt: "2026-06-07",
    relatedPostSlugs: ["nen-chon-wifi-mesh-hay-router-phu"],
    featured: true,
  }),
  post(8, {
    slug: "nen-chon-wifi-mesh-hay-router-phu",
    title: "Nên chọn WiFi Mesh hay router phụ?",
    excerpt: "So sánh chi phí, độ ổn định và trải nghiệm giữa Mesh và router phụ.",
    content: `<p>Router phụ rẻ hơn nhưng dễ có 2 mạng riêng, chuyển sóng không mượt. Mesh đồng bộ hơn, giá cao hơn.</p><h2>Gợi ý</h2><p>Nhà nhỏ 1 tầng: thử đổi vị trí modem trước. Nhà rộng: cân nhắc Mesh VNPT.</p>`,
    category: "wifi",
    tags: ["Mesh", "router phụ"],
    seoTitle: "WiFi Mesh hay router phụ — nên chọn gì?",
    seoDescription: "So sánh WiFi Mesh và router phụ để chọn giải pháp phù hợp.",
    readingTime: 4,
    publishedAt: "2026-06-08",
    relatedPostSlugs: ["wifi-mesh-la-gi"],
  }),
  post(9, {
    slug: "sim-5g-vnpt-co-can-doi-sim",
    title: "SIM 5G VNPT có cần đổi SIM không?",
    excerpt: "Khi nào SIM 4G cũ cần đổi USIM mới để dùng 5G VNPT.",
    content: `<p>SIM 4G đời cũ có thể không hỗ trợ 5G. Cần kiểm tra loại SIM trên máy hoặc tại quầy.</p><h2>Cách kiểm tra</h2><p>Gửi ảnh SIM hoặc IMEI qua Zalo, tôi hỗ trợ kiểm tra trước khi đổi.</p>`,
    category: "sim-5g",
    tags: ["5G", "đổi SIM"],
    seoTitle: "SIM 5G VNPT có cần đổi SIM không?",
    seoDescription: "Có cần đổi SIM để dùng 5G VNPT không? Hướng dẫn kiểm tra.",
    readingTime: 3,
    publishedAt: "2026-06-09",
    relatedPostSlugs: ["esim-vnpt-la-gi"],
  }),
  post(10, {
    slug: "esim-vnpt-la-gi",
    title: "eSIM VNPT là gì? Ưu nhược điểm so với SIM vật lý",
    excerpt: "eSIM kích hoạt qua QR, không cần giao SIM — phù hợp điện thoại hỗ trợ eSIM.",
    content: `<p>eSIM là SIM điện tử nhúng trong máy. Kích hoạt bằng QR code từ nhà mạng.</p><h2>Ưu điểm</h2><p>Tiện, nhanh, dùng song SIM ảo. Nhược: không phải mọi máy đều hỗ trợ.</p>`,
    category: "sim-5g",
    tags: ["eSIM", "VNPT"],
    seoTitle: "eSIM VNPT là gì?",
    seoDescription: "Giải thích eSIM VNPT, cách dùng và so với SIM vật lý.",
    readingTime: 4,
    publishedAt: "2026-06-10",
    relatedPostSlugs: ["cach-kich-hoat-esim-vnpt"],
  }),
  post(11, {
    slug: "cach-kich-hoat-esim-vnpt",
    title: "Cách kích hoạt eSIM VNPT trên iPhone và Android",
    excerpt: "Hướng dẫn từng bước quét QR và cấu hình eSIM VNPT.",
    content: `<p>Cần WiFi khi kích hoạt lần đầu. Vào Cài đặt → Di động → Thêm eSIM → quét QR.</p><h2>Lỗi thường gặp</h2><p>QR hết hạn, máy không hỗ trợ eSIM, hoặc chưa cập nhật iOS/Android mới.</p>`,
    category: "sim-5g",
    tags: ["eSIM", "kích hoạt"],
    seoTitle: "Cách kích hoạt eSIM VNPT",
    seoDescription: "Hướng dẫn kích hoạt eSIM VNPT trên điện thoại từng bước.",
    readingTime: 5,
    publishedAt: "2026-06-11",
    relatedPostSlugs: ["esim-vnpt-la-gi"],
  }),
  post(12, {
    slug: "apn-5g-vnpt",
    title: "APN 5G VNPT — cấu hình khi data không lên",
    excerpt: "Cài APN đúng để kết nối 5G/4G VNPT ổn định trên Android và iPhone.",
    content: `<p>APN sai là nguyên nhân phổ biến khié data chập chờn sau đổi SIM.</p><h2>Cách cấu hình</h2><p>Vào cài đặt mạng di động, thêm APN theo hướng dẫn VNPT. Khởi động lại máy sau khi lưu.</p>`,
    category: "troubleshooting",
    tags: ["APN", "5G"],
    seoTitle: "APN 5G VNPT — cấu hình đúng",
    seoDescription: "Hướng dẫn cấu hình APN 5G VNPT khi mạng data không ổn định.",
    readingTime: 4,
    publishedAt: "2026-06-12",
    relatedPostSlugs: ["sim-5g-vnpt-co-can-doi-sim"],
  }),
  post(13, {
    slug: "goi-5g-vnpt-nao-phu-hop",
    title: "Gói 5G VNPT nào phù hợp với bạn?",
    excerpt: "Chọn gói 5G theo mức dùng: lướt web, xem video, livestream hay hotspot.",
    content: `<p>Gói nhỏ cho Zalo, map. Gói trung cho video và học online. Gói lớn cho livestream và hotspot laptop.</p><h2>Mẹo</h2><p>Theo dõi data 1 tuần trước khi chọn gói tháng.</p>`,
    category: "sim-5g",
    tags: ["gói 5G", "data"],
    seoTitle: "Gói 5G VNPT nào phù hợp?",
    seoDescription: "Cách chọn gói 5G VNPT theo nhu cầu sử dụng thực tế.",
    readingTime: 4,
    publishedAt: "2026-06-13",
    relatedPostSlugs: ["sim-5g-vnpt-co-can-doi-sim"],
  }),
  post(14, {
    slug: "camera-vnpt-co-luu-cloud-khong",
    title: "Camera VNPT có lưu cloud không?",
    excerpt: "Giải thích gói cloud 7–30 ngày và cách chọn theo nhu cầu.",
    content: `<p>Camera VNPT hỗ trợ lưu cloud theo gói. Gia đình thường 7 ngày, cửa hàng nên 30 ngày.</p><h2>Chi phí</h2><p>Phí cloud tính hàng tháng, tôi giải thích rõ khi tư vấn lắp.</p>`,
    category: "camera",
    tags: ["cloud", "camera"],
    seoTitle: "Camera VNPT có lưu cloud không?",
    seoDescription: "Camera VNPT lưu cloud thế nào? Gói và cách chọn phù hợp.",
    readingTime: 3,
    publishedAt: "2026-06-14",
    relatedPostSlugs: ["lap-camera-gia-dinh-can-luu-y-gi"],
  }),
  post(15, {
    slug: "camera-wifi-hay-bi-mat-ket-noi",
    title: "Camera WiFi hay bị mất kết nối — nguyên nhân và cách xử lý",
    excerpt: "Camera offline thường do WiFi yếu, không phải hỏng thiết bị.",
    content: `<p>Kiểm tra sóng WiFi tại vị trí camera trước. Nếu yếu, di chuyển router, thêm Mesh hoặc dùng camera có dây.</p><h2>Tip</h2><p>Đặt camera không quá xa modem, tránh tường dày và góc khuất.</p>`,
    category: "troubleshooting",
    tags: ["camera", "WiFi"],
    seoTitle: "Camera WiFi hay mất kết nối — xử lý thế nào?",
    seoDescription: "Nguyên nhân camera WiFi hay offline và cách khắc phục.",
    readingTime: 4,
    publishedAt: "2026-06-15",
    relatedPostSlugs: ["nen-lap-camera-wifi-hay-camera-co-day"],
  }),
  post(16, {
    slug: "nen-lap-camera-wifi-hay-camera-co-day",
    title: "Nên lắp camera WiFi hay camera có dây?",
    excerpt: "So sánh độ ổn định, chi phí lắp và phù hợp từng loại nhà/cửa hàng.",
    content: `<p>WiFi linh hoạt, dễ lắp. Có dây ổn định hơn cho giám sát 24/7. Cửa hàng nên cân nhắc có dây/PoE.</p>`,
    category: "camera",
    tags: ["camera WiFi", "camera có dây"],
    seoTitle: "Camera WiFi hay có dây — nên chọn gì?",
    seoDescription: "So sánh camera WiFi và camera có dây cho gia đình và cửa hàng.",
    readingTime: 4,
    publishedAt: "2026-06-16",
    relatedPostSlugs: ["camera-wifi-hay-bi-mat-ket-noi"],
  }),
  post(17, {
    slug: "lap-camera-gia-dinh-can-luu-y-gi",
    title: "Lắp camera gia đình cần lưu ý gì?",
    excerpt: "Vị trí lắp, quyền riêng tư, WiFi và gói cloud — checklist trước khi lắp.",
    content: `<p>Chọn vị trí không vi phạm riêng tư hàng xóm. Đảm bảo WiFi ổn định. Chọn gói cloud phù hợp.</p><h2>Checklist</h2><ul><li>Số camera cần</li><li>Góc quan sát</li><li>WiFi/Mesh</li><li>Cloud bao nhiêu ngày</li></ul>`,
    category: "camera",
    tags: ["lắp camera", "gia đình"],
    seoTitle: "Lắp camera gia đình cần lưu ý gì?",
    seoDescription: "Checklist lắp camera gia đình: vị trí, WiFi, cloud và quyền riêng tư.",
    readingTime: 5,
    publishedAt: "2026-06-17",
    relatedPostSlugs: ["camera-vnpt-co-luu-cloud-khong"],
  }),
  post(18, {
    slug: "internet-vnpt-va-wifi-mesh-cho-nha-nhieu-tang",
    title: "Internet VNPT và WiFi Mesh cho nhà nhiều tầng",
    excerpt: "Kết hợp gói Internet tốc độ cao với Mesh để phủ sóng đều mọi tầng.",
    content: `<p>Nhà 2–3 tầng cần cả băng thông đủ và phủ sóng đều. Gói 500 Mbps + 2 node Mesh là combo phổ biến.</p><h2>Survey miễn phí</h2><p>Liên hệ tôi để khảo sát vị trí đặt node Mesh tại Quận 12.</p>`,
    category: "wifi",
    tags: ["Mesh", "nhiều tầng"],
    seoTitle: "Internet VNPT + WiFi Mesh cho nhà nhiều tầng",
    seoDescription: "Giải pháp Internet VNPT kết hợp Mesh cho nhà 2–3 tầng.",
    readingTime: 4,
    publishedAt: "2026-06-18",
    relatedPostSlugs: ["wifi-mesh-la-gi"],
  }),
  post(19, {
    slug: "speedtest-cao-nhung-video-van-lag",
    title: "Speedtest cao nhưng video vẫn lag — vì sao?",
    excerpt: "Bufferbloat, WiFi nhiễu, server video và số thiết bị — nguyên nhân thực tế.",
    content: `<p>Speedtest chỉ đo tốc độ tại một thời điểm. Video lag có thể do nhiễu WiFi, nhiều thiết bị cùng tải, hoặc server video.</p><h2>Cách xử lý</h2><p>Test bằng dây LAN, giảm thiết bị, đổi kênh WiFi, restart modem.</p>`,
    category: "troubleshooting",
    tags: ["speedtest", "lag"],
    seoTitle: "Speedtest cao nhưng video vẫn lag?",
    seoDescription: "Tại sao speedtest cao mà xem video vẫn giật? Nguyên nhân và cách xử lý.",
    readingTime: 4,
    publishedAt: "2026-06-19",
    relatedPostSlugs: ["wifi-yeu-phai-lam-gi"],
  }),
  post(20, {
    slug: "internet-gia-dinh-tu-rot-roi-co-lai",
    title: "Internet gia đình tự rớt rồi có lại — xử lý thế nào?",
    excerpt: "Mạng chập chờn, tự mất rồi có lại: modem, dây, nhà mạng hay WiFi?",
    content: `<p>Hiện tượng rớt rồi có lại thường do modem quá nhiệt, dây LAN lỏng, hoặc sự cố tạm từ nhà mạng.</p><h2>Thử trước</h2><p>Restart modem, kiểm tra dây, ghi lại thời gian rớt. Nếu lặp lại nhiều lần, liên hệ hỗ trợ.</p>`,
    category: "troubleshooting",
    tags: ["mất mạng", "internet"],
    seoTitle: "Internet tự rớt rồi có lại — xử lý thế nào?",
    seoDescription: "Internet gia đình hay tự mất rồi có lại? Nguyên nhân và cách khắc phúc.",
    readingTime: 3,
    publishedAt: "2026-06-20",
    relatedPostSlugs: ["wifi-yeu-phai-lam-gi", "speedtest-cao-nhung-video-van-lag"],
  }),
];
